kind: pipeline
name: default

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
    when:
      event: [pull_request, tag]

  - name: test
    image: golang:1.13.7
    volumes:
      - name: deps
        path: /go
    commands:
      - make ci
    depends_on: [clone]
    when:
      event: [pull_request]

  - name: validate commits
    image: golang:1.13.7
    volumes:
      - name: deps
        path: /go
    commands:
      - go run main.go
    depends_on: [clone]
    when:
      event: [pull_request]

  # This is here for backwards compatibility for repos using old naming
  - name: deprecated-docker
    image: plugins/docker
    settings:
      auto_tag: true
      repo: commitsar/commitsar
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: docker
    image: plugins/docker
    settings:
      auto_tag: true
      repo: outillage/commitsar
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: publish-pages
    image: commitsar/hugo
    environment:
      USERNAME:
        from_secret: github_username
      PASSWORD:
        from_secret: github_token
    commands:
      - echo "machine github.com login $${USERNAME} password $${PASSWORD}" > ~/.netrc
      - git fetch --all
      - git config --global user.email "bot@commitsar.tch"
      - git config --global user.name "Commitsar Bot"
      - cd www
      - npm i
      - sh ../scripts/publish_to_pages.sh
    when:
      event: push
      branch: master

volumes:
  - name: deps
    temp: {}
