# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# Make sure to check the documentation at https://goreleaser.com
version: 2

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    goos:
      - windows
      - linux
      - darwin

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  disable: true
