name: "Commitsar Action"
description: "Check commit message compliance with conventional commits"
author: "Simon Prochazka"
branding:
  icon: "code"
  color: "blue"
inputs:
  config:
    description: "Path of the Commitsar config file"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
