name: "Commitsar Action"
description: "Check commit message compliance with conventional commits"
author: "Simon Prochazka"
branding:
  icon: "code"
  color: "blue"
inputs:
runs:
  using: "docker"
  image: "Dockerfile"
