name: "Commitsar Action"
description: "Check commit message compliance with conventional commits"
author: "Simon Prochazka"
branding:
  icon: "code"
  color: "blue"
inputs:
  config:
    description: "Path to the folder where your .commitsar.yaml is"
    required: false
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - commitsar
    - "--config-path=${{ inputs.config }}"
